jwt:
  secret: 'FXjG[>tR5p}jclOt#h}h~l<;u9..[/r*D|&gdqDmzDZ9I!EEe7Cz/c"cpTibR5'

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebanking
    password:
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
